name: Build XDNS Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', topic/RDK*, develop ]

jobs:
  build-xdns-on-pr:
    name: Build XDNS component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: native build
        run: |
          chmod +x cov_docker_script/run_setup_dependencies.sh
          ./cov_docker_script/run_setup_dependencies.sh
          chmod +x cov_docker_script/run_native_build.sh
          ./cov_docker_script/run_native_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}