name: PR Format Check

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: pr-format-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    uses: rdkcentral/build_tools_workflows/.github/workflows/pr-lint.yml@develop
